SET FOREIGN_KEY_CHECKS=1;
CREATE DATABASE IF NOT EXISTS istruttori;
use istruttori;
-- drop tables list
DROP TABLE IF EXISTS Programma;
DROP TABLE IF EXISTS Istruttore;
DROP TABLE IF EXISTS Attivita;
CREATE TABLE IF NOT EXISTS Istruttore (
	CodFisc VARCHAR(15) UNIQUE NOT NULL ,
	Nome VARCHAR(255) NOT NULL ,
	Cognome VARCHAR(255) NOT NULL ,
	DataN DATE NOT NULL ,
	Titolo VARCHAR(255) NOT NULL ,
	Email VARCHAR(255) NOT NULL ,
	Tel VARCHAR(255) NULL ,
	PRIMARY KEY (CodFisc)
);

CREATE TABLE IF NOT EXISTS Attivita (
	CodA VARCHAR(255) UNIQUE NOT NULL ,
	TipoA VARCHAR(255) NOT NULL ,
	Nome VARCHAR(255) NULL ,
	Livello ENUM('1', '2', '3', '4'),
	PRIMARY KEY (CodA)
);

CREATE TABLE IF NOT EXISTS Programma (
	CodFisc VARCHAR(15) NOT NULL ,
	Giorno VARCHAR(15) NOT NULL ,
	OraI TIME NOT NULL ,
	OraF TIME NOT NULL ,
	Sala ENUM('1', '2', '3', '4', '10'),
	CodA VARCHAR(255) NOT NULL ,
	PRIMARY KEY (CodFisc,Giorno,OraI) ,
	FOREIGN KEY (CodFisc )
		REFERENCES Istruttore(CodFisc )
		ON DELETE CASCADE
		ON UPDATE CASCADE ,
	FOREIGN KEY (CodA )
		REFERENCES Attivita(CodA )
		ON DELETE CASCADE
		ON UPDATE CASCADE
);